name: Leirvassbu-varsel

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
      test:
        description: "Send testvarsel"
        type: boolean
        default: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - run: python3 check.py
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
          TEST: ${{ inputs.test }}
